#!/usr/bin/env perl
use Mojo::Base -strict;
use FindBin;
use lib "$FindBin::Bin/../lib";
use FediVid;

my $app = FediVid->new;
$app->pg->migrations
         ->from_file($app->home->rel_file('migrations.sql'))
         ->migrate;

say 'migrations applied to ' . $app->config('database_url');
